version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: finance
      MYSQL_USER: finance
      MYSQL_PASSWORD: finance
    ports:
      - "3307:3306"

